### ISSUE TITLE
Potential Memory Leak with Galacticraft Venus

### ISSUE THREAD

**Issue by skiprocks999** [jaskarth/fabric-chunkpregenerator#12]
Hello,
I have noticed an interesting issue when trying to pregenerate chunks in the Galacticraft Venus dimension. For reference, I am running it on a modded 1.12.2 server with Forge v. 14.23.5.2855 and Chunk Pregenerator v. 1.12-2.4.1. The server itself is running ~238 mods.

For whatever reason, the memory usage of the pregenerator will keep going up until it crashes the server. Now to clarify, the garbage collector is working, but the "baseline" ram usage if you will keeps increasing. 

I have not had this issue with any of the other Galacticraft dimensions, nor any other dimensions for that matter. I have tried running the pregenerator on multiple settings, all to the same effect. 

It's really hard to provide any useful crash logs, or logs of any kind for that matter, as all they state is that the server ran out of memory due to the pregenerator reaching max memory capacity. I can provide them however if you would like. 

Is this a known issue?

**Comment by Speiger** [comment]
You are on the wrong Chunk Pregenerator. You are talking about my pregenerator not SuperCoders.
