### ISSUE TITLE
Pregen eats up memory

### ISSUE THREAD

**Issue by crdtrd** [jaskarth/fabric-chunkpregenerator#15]
I was monitoring a pregen of the end dimension with spark and found that the pregen was causing the memory to be filled up, being stored in old generation memory. Ultimately caused a server crash. The server has 6Gb of memory. I am using the mod version 0.3.4 for 1.17

**Comment by TerdyTheTerd** [comment]
This might be a deeper issue with the end. Another pregen mod Chunky has the same issue with the end, other dims ran fine for 4 days.

**Comment by pop4959** [comment]
> This might be a deeper issue with the end. Another pregen mod Chunky has the same issue with the end, other dims ran fine for 4 days.

Did you upgrade a world from 1.17 to 1.18? In that case it's likely that the issue could be [MC-245406](https://bugs.mojang.com/browse/MC-245406).

**Comment by crdtrd** [comment]
I've since started a new world for 1.18 and used Chunky for that. I don't recall running into any problems like in last version.

**Comment by pop4959** [comment]
> I've since started a new world for 1.18 and used Chunky for that. I don't recall running into any problems like in last version, although I do notice that generation may start at a fairly higher speed than it ends with (with all the pregen mods I've used), but that's probably a different issue.

Higher speed at the start is usually because the spawn is already generated, new gen is always slower

**Comment by TerdyTheTerd** [comment]
Just to keep you updated. Chunky was having an issue with the End for whatever reason. I had zero issue with this mod after running it for 10 hours, I was falsely under the impression there was an issue when there wasn.t.
